on:
  create:
    tags:
      - '^v\d+\.\d+\.\d+(-rc.\d+|)'

name: release

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - run: git fetch --prune --unshallow
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - run: npm run get-changelog | tail -n +2
      - name: Get latest changelog
        id: Changelog
        run: |
          changelog=$(npm run --silent get-changelog | tail -n +2)
          echo $changelog
          changelog="${changelog//'%'/'%25'}"
          changelog="${changelog//$'\n'/'%0A'}"
          changelog="${changelog//$'\r'/'%0D'}"
          echo "::set-output name=changelog::$changelog"
      - name: Get release type
        id: release_type
        run: |
          PRERELEASE=$([[ ${{ github.ref }} == *"-rc"* ]] && echo true || echo false)
          echo "::set-output name=prerelease::$PRERELEASE"
      - name: Create github release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          draft: false
          prerelease: ${{ steps.release_type.outputs.prerelease }}

  publish-npm:
    name: Publish to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build --if-present
      - name: Get npm tag
        id: npm_tag
        run: |
          NPM_TAG=$([[ ${{ github.ref }} == *"-rc"* ]] && echo "next" || echo "latest")
          echo "::set-output name=tag::$NPM_TAG"
      - name: Publish
        run: npm publish --tag ${{ steps.npm_tag.outputs.tag }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  # publish-gh:
  #   name: Publish to github packages
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: 14
  #         registry-url: https://npm.pkg.github.com/
  #     - name: Install dependencies
  #       run: npm ci
  #     - name: Build
  #       run: npm run build --if-present
  #     - name: Get npm tag
  #       id: npm_tag
  #       run: |
  #         NPM_TAG=$([[ ${{ github.ref }} == *"-rc"* ]] && echo "next" || echo "latest")
  #         echo "::set-output name=tag::$NPM_TAG"
  #     - run: npm publish --access public
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
